//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_day {
            get {
                object obj = ResourceManager.GetObject("clear_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_night {
            get {
                object obj = ResourceManager.GetObject("clear_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloudy {
            get {
                object obj = ResourceManager.GetObject("cloudy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fog {
            get {
                object obj = ResourceManager.GetObject("fog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amsterdam:52.379189,4.899431
        ///Budapest:47.49801,19.03991
        ///Debrecen:47.53333,21.63333
        ///Luxembourg:49.611622,6.131935
        ///Pécs:46.08333,18.23333
        ///Prague:50.08804,14.42076
        ///München:48.137154,11.576124
        ///Wienna:48.210033,16.363449.
        /// </summary>
        internal static string ListOfCities {
            get {
                return ResourceManager.GetString("ListOfCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear-day, 
        ///clear-night, 
        ///rain, 
        ///snow,
        ///sleet, 
        ///wind, 
        ///fog, 
        ///cloudy, 
        ///partly-cloudy-day,
        ///partly-cloudy-night.
        ///thunderstorm, 
        ///tornado.
        /// </summary>
        internal static string listOfIcon {
            get {
                return ResourceManager.GetString("listOfIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar:Arabic
        ///az:Azerbaijani
        ///be:Belarusian
        ///bg:Bulgarian
        ///bn:Bengali
        ///bs:Bosnian
        ///ca:Catalan
        ///cs:Czech
        ///da:Danish
        ///de:German
        ///el:Greek
        ///en:English (which is the default)
        ///eo:Esperanto
        ///es:Spanish
        ///et:Estonian
        ///fi:Finnish
        ///fr:French
        ///he:Hebrew
        ///hi:Hindi
        ///hr:Croatian
        ///hu:Hungarian
        ///id:Indonesian
        ///is:Icelandic
        ///it:Italian
        ///ja:Japanese
        ///ka:Georgian
        ///kn:Kannada
        ///ko:Korean
        ///kw:Cornish
        ///lv:Latvian
        ///ml:Malayam
        ///mr:Marathi
        ///nb:Norwegian Bokmål
        ///nl:Dutch
        ///no:Norwegian Bokmål (alias for nb)
        ///pa:Punjabi
        ///pl:Polish
        ///pt:Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListOfLanguages {
            get {
                return ResourceManager.GetString("ListOfLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap partly_cloudy_day {
            get {
                object obj = ResourceManager.GetObject("partly_cloudy_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap partly_cloudy_night {
            get {
                object obj = ResourceManager.GetObject("partly_cloudy_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain {
            get {
                object obj = ResourceManager.GetObject("rain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sleet {
            get {
                object obj = ResourceManager.GetObject("sleet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snow {
            get {
                object obj = ResourceManager.GetObject("snow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thunderstorm {
            get {
                object obj = ResourceManager.GetObject("thunderstorm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tornado {
            get {
                object obj = ResourceManager.GetObject("tornado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wind {
            get {
                object obj = ResourceManager.GetObject("wind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
